# Generated by Django 4.1.7 on 2023-04-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.CharField(max_length=255)),
                ('workers', models.CharField(max_length=255)),
            ],
        ),
    ]
