# Generated by Django 4.1.7 on 2023-04-02 20:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clicker_game', '0002_clicker_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clicker',
            new_name='ClickerDetails',
        ),
    ]
