# Generated by Django 4.1.7 on 2023-05-16 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clicker_game', '0002_alter_cursor_cursorcost_alter_cursor_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clickerdetails',
            old_name='workers',
            new_name='totalIncrementBy',
        ),
    ]
