# Generated by Django 4.1.7 on 2023-05-16 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clicker_game', '0003_rename_workers_clickerdetails_totalincrementby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clickerdetails',
            old_name='totalIncrementBy',
            new_name='total_increment_by',
        ),
        migrations.RenameField(
            model_name='cursor',
            old_name='cursorCost',
            new_name='cursor_cost',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='incrementBy',
            new_name='increment_by',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='workerCost',
            new_name='worker_cost',
        ),
    ]
