# Generated by Django 4.1.7 on 2023-05-18 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clicker_game', '0004_rename_totalincrementby_clickerdetails_total_increment_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upgrade_type', models.CharField(choices=[('worker', 'Worker'), ('cursor', 'Cursor')], max_length=255)),
                ('cost', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('increment_by', models.CharField(max_length=255)),
                ('clicker_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clicker_game.clickerdetails')),
            ],
        ),
        migrations.RemoveField(
            model_name='worker',
            name='clicker_details',
        ),
        migrations.DeleteModel(
            name='Cursor',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
