# Generated by Django 4.1.7 on 2023-05-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker_game', '0006_remove_upgrade_increment_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgrade',
            name='auto_increment_by',
            field=models.CharField(default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='value',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
