# Generated by Django 4.1.7 on 2023-05-31 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clicker_game', '0008_alter_upgrade_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='upgrade',
            managers=[
            ],
        ),
    ]
